<#
.SYNOPSIS
  为 snapshot_tree.txt 每行追加中文注释说明，生成 snapshot_tree_zh.txt。

.DESCRIPTION
  读取 oa_project_snapshot.ps1 产出的 snapshot_tree.txt（UTF-16 BE），
  对每个文件/目录项追加中文功能描述，输出为 UTF-8 编码的
  snapshot_tree_zh.txt，便于团队快速了解项目结构。

.NOTES
  执行顺序：此脚本应在 oa_project_snapshot.ps1 之后执行。
  注意事项：
  - snapshot_tree.txt 必须已存在（由 oa_project_snapshot.ps1 生成）
  - 输入文件编码为 UTF-16 BigEndian，不可随意另存
  - 输出文件编码为 UTF-8（含 BOM），适合 git 跟踪
  - 内置描述字典以文件/目录名匹配，同名项（如 examples
    出现在 images/ panels/ scripts/ 下）会根据父目录上下文
    自动匹配不同描述
  - 新增文件/目录时需同步更新 $desc 字典
  - 请在项目根目录下运行
#>

$inputFile = "snapshot_tree.txt"
$outputFile = "snapshot_tree_zh.txt"

$lines = Get-Content -LiteralPath $inputFile -Encoding BigEndianUnicode

$desc = @{}

$desc["oa_project_snapshot.ps1"] = "项目快照 PowerShell 脚本"
$desc["snapshot_files.txt"]      = "项目文件清单快照"
$desc["snapshot_tree.txt"]       = "项目目录树快照"
$desc["bin"]                     = "WinCC OA 可执行文件/驱动程序目录"
$desc["colorDB"]                 = "颜色数据库目录"
$desc["config"]                  = "项目配置目录"
$desc["certificate.pem"]         = "服务器 SSL 证书文件"
$desc["host-cert.pem"]           = "主机 SSL 证书文件"
$desc["host-key.pem"]            = "主机 SSL 私钥文件"
$desc["progs"]                   = "程序启动配置列表"
$desc["root-cert.pem"]           = "根 CA 证书文件"
$desc["data"]                    = "运行数据目录"
$desc["iec104"]                  = "IEC 60870-5-104 协议数据"
$desc["PKI"]                     = "公钥基础设施证书目录"
$desc["certs"]                   = "已签发证书目录"
$desc["crl"]                     = "证书吊销列表目录"
$desc["private"]                 = "私钥目录"
$desc["iec.crt"]                 = "IEC 104 通信证书"
$desc["iecRoot.crt"]             = "IEC 104 根证书"
$desc["iec.key"]                 = "IEC 104 通信私钥"
$desc["iecRoot.key"]             = "IEC 104 根私钥"
$desc["empty.del"]               = "占位空文件(保持目录结构)"
$desc["opcua"]                   = "OPC UA 通信协议数据"
$desc["client"]                  = "OPC UA 客户端数据"
$desc["server"]                  = "OPC UA 服务器数据"
$desc["CA"]                      = "证书颁发机构目录"
$desc["issuers"]                 = "证书颁发者目录"
$desc["rejected"]                = "被拒证书目录"
$desc["WinCC_OA_UA_Client.der"]  = "OPC UA 客户端 DER 格式证书"
$desc["WinCC_OA_UA_Server.der"]  = "OPC UA 服务器 DER 格式证书"
$desc["WinCC_OA_UA_Client.pem"]  = "OPC UA 客户端 PEM 格式私钥"
$desc["WinCC_OA_UA_Server.pem"]  = "OPC UA 服务器 PEM 格式私钥"
$desc["rcp"]                     = "远程控制协议(RCP)数据"
$desc["rct"]                     = "运行数据收集(RCT)数据"
$desc["Reporting"]               = "报表服务数据"
$desc["Reporting.wsdl"]          = "报表服务 WSDL 接口定义"
$desc["Reporting_document_literal.wsdl"] = "报表服务文档风格 WSDL"
$desc["Templates"]               = "报表模板目录"
$desc["BIRT"]                    = "BIRT 报表模板目录"
$desc["InformationServer"]       = "InformationServer 报表模板目录"
$desc["alertGetPeriod_1DPE_Table.rptdesign"] = "报警周期查询表格 BIRT 报表"
$desc["dpGetPeriod_1DPE_Line_2D.rptdesign"]  = "数据点周期查询折线图 BIRT 报表"
$desc["dpGetPeriod_2DPE_Bar_2D.rptdesign"]   = "数据点两周期对比柱状图 BIRT 报表"
$desc["dpGetPeriod_2DPE_Bar_3D.rptdesign"]   = "数据点两周期对比 3D 柱状图 BIRT 报表"
$desc["dpGetPeriod_4DPE_Bar_2D.rptdesign"]   = "数据点四周期对比柱状图 BIRT 报表"
$desc["dpQuery_alarms_Timerange_Table.rptdesign"] = "报警时间范围查询表格 BIRT 报表"
$desc["dpQuery_AlertsCount_Bar_2D.rptdesign"]     = "报警计数柱状图 BIRT 报表"
$desc["dpQuery_Value_Bar_2D.rptdesign"]           = "数值查询柱状图 BIRT 报表"
$desc["dpQuery_Value_Pie_2D.rptdesign"]           = "数值查询饼图 BIRT 报表"
$desc["dpQuery_Value_Pie_3D.rptdesign"]           = "数值查询 3D 饼图 BIRT 报表"
$desc["localization.properties"]        = "本地化属性默认配置"
$desc["localization_de_AT.properties"]  = "奥地利德语本地化属性"
$desc["WinCC_OA_AlarmTable.rdl"]        = "报警表格 RDL 报表定义"
$desc["WinCC_OA_LineChart.rdl"]         = "折线图 RDL 报表定义"
$desc["sounds"]                  = "声音文件目录"
$desc["TIA_Projects"]            = "TIA Portal 项目集成目录"
$desc["xls_report"]              = "Excel 报表模板目录"
$desc["ATVTemplate.xltm"]        = "ATV Excel 报表模板"
$desc["CstTemplate.xltm"]        = "CST Excel 报表模板"
$desc["OprTemplate.xltm"]        = "OPR Excel 报表模板"
$desc["Report.cmd"]              = "报表生成命令行脚本"
$desc["Report.mdb"]              = "报表 Access 数据库"
$desc["Report.xls"]              = "报表 Excel 文件"
$desc["SQLTemplate.xltm"]        = "SQL 查询 Excel 报表模板"
$desc["StdTemplate.xltm"]        = "标准 Excel 报表模板"
$desc["db"]                      = "项目数据库目录"
$desc["lta"]                     = "长期归档(LTA)数据库"
$desc["wincc_oa"]                = "项目核心 RAID 数据库"
$desc["alertcl.db"]              = "报警客户端数据库"
$desc["alertcl.key"]             = "报警客户端数据库索引"
$desc["alertdir.db"]             = "报警目录数据库"
$desc["AlertDir.dbd"]            = "报警目录数据库定义"
$desc["alertdir.key"]            = "报警目录数据库索引"
$desc["alertrr.db"]              = "报警轮询记录数据库"
$desc["alertval.db"]             = "报警值数据库"
$desc["alertval.key"]            = "报警值数据库索引"
$desc["aliasId.db"]              = "别名 ID 数据库"
$desc["aliasId.key"]             = "别名 ID 数据库索引"
$desc["archclass.db"]            = "归档类别数据库"
$desc["archclass.key"]           = "归档类别数据库索引"
$desc["archinfo.db"]             = "归档信息数据库"
$desc["archinfo.key"]            = "归档信息数据库索引"
$desc["archproc.db"]             = "归档处理数据库"
$desc["attrId.db"]               = "属性 ID 数据库"
$desc["bgacstat.db"]             = "后台归档状态数据库"
$desc["bgacstat.key"]            = "后台归档状态数据库索引"
$desc["bgavgpp.db"]              = "后台平均值预处理数据库"
$desc["bgavgpp.key"]             = "后台平均值预处理数据库索引"
$desc["bgdpel.db"]               = "后台数据点元素数据库"
$desc["bglcstat.db"]             = "后台线性插值状态数据库"
$desc["bglcstat.key"]            = "后台线性插值状态数据库索引"
$desc["bgldpel.db"]              = "后台线性插值数据点元素数据库"
$desc["bgoastat.db"]             = "后台原始值归档状态数据库"
$desc["bgoastat.key"]            = "后台原始值归档状态数据库索引"
$desc["bgolstat.db"]             = "后台原始值日志状态数据库"
$desc["bgolstat.key"]            = "后台原始值日志状态数据库索引"
$desc["BgStatus.dbd"]            = "后台状态数据库定义"
$desc["bgudpel.db"]              = "后台用户数据点元素数据库"
$desc["bguint.db"]               = "后台无符号整型数据库"
$desc["bguint.key"]              = "后台无符号整型数据库索引"
$desc["bgupdfv.db"]              = "后台更新过滤值数据库"
$desc["bgupdfv.key"]             = "后台更新过滤值数据库索引"
$desc["bit32var.db"]             = "32 位位变量数据库"
$desc["bit64va.db"]              = "64 位位变量数据库"
$desc["bitvar.db"]               = "位变量数据库"
$desc["charvar.db"]              = "字符变量数据库"
$desc["cnsTree.db"]              = "控制台导航树数据库"
$desc["cnsView.db"]              = "控制台视图数据库"
$desc["ConfHist.dbd"]            = "配置历史数据库定义"
$desc["confId.db"]               = "配置 ID 数据库"
$desc["confId.key"]              = "配置 ID 数据库索引"
$desc["conv.db"]                 = "转换表数据库"
$desc["conv.key"]                = "转换表数据库索引"
$desc["dbdir.db"]                = "数据库目录数据库"
$desc["DbDir.dbd"]               = "数据库目录数据库定义"
$desc["dbdir.key"]               = "数据库目录数据库索引"
$desc["dflvalh.db"]              = "默认值句柄数据库"
$desc["dflvalh.key"]             = "默认值句柄数据库索引"
$desc["distdrv.key"]             = "分布式驱动数据库索引"
$desc["distinfo.db"]             = "分布式信息数据库"
$desc["distinfo.key"]            = "分布式信息数据库索引"
$desc["dpauth.db"]               = "数据点授权数据库"
$desc["dpauth.key"]              = "数据点授权数据库索引"
$desc["dpfunc.db"]               = "数据点函数数据库"
$desc["dpfunc.key"]              = "数据点函数数据库索引"
$desc["dpId.db"]                 = "数据点 ID 数据库"
$desc["dpId.key"]                = "数据点 ID 数据库索引"
$desc["dpidvar.db"]              = "数据点 ID 变量数据库"
$desc["dynvar.db"]               = "动态变量数据库"
$desc["elId.db"]                 = "元素 ID 数据库"
$desc["fixId.db"]                = "固定 ID 数据库"
$desc["fixId.key"]               = "固定 ID 数据库索引"
$desc["floatvar.db"]             = "浮点变量数据库"
$desc["genattr.db"]              = "通用属性数据库"
$desc["genconf.db"]              = "通用配置数据库"
$desc["genconf.key"]             = "通用配置数据库索引"
$desc["intvar.db"]               = "整型变量数据库"
$desc["lngvar.db"]               = "长整型变量数据库"
$desc["objName.db"]              = "对象名称数据库"
$desc["objNameTxt.db"]           = "对象名称文本数据库"
$desc["peradr.db"]               = "周期地址数据库"
$desc["peradr.key"]              = "周期地址数据库索引"
$desc["pvssGlobal.db"]           = "PVSS 全局数据库"
$desc["pvssrng.db"]              = "PVSS 范围数据库"
$desc["pvssrng.key"]             = "PVSS 范围数据库索引"
$desc["rngrec.db"]               = "范围记录数据库"
$desc["sconv.db"]                = "字符串转换数据库"
$desc["sconvatt.db"]             = "字符串转换属性数据库"
$desc["sconvi.db"]               = "字符串转换输入数据库"
$desc["smooth.db"]               = "平滑数据库"
$desc["smooth.key"]              = "平滑数据库索引"
$desc["smthattr.db"]             = "平滑属性数据库"
$desc["sysId.db"]                = "系统 ID 数据库"
$desc["sysId.key"]               = "系统 ID 数据库索引"
$desc["textvar.db"]              = "文本变量数据库"
$desc["timevar.db"]              = "时间变量数据库"
$desc["TypeAndId.dbd"]           = "类型与 ID 数据库定义"
$desc["typeId.db"]               = "类型 ID 数据库"
$desc["typeId.key"]              = "类型 ID 数据库索引"
$desc["uintvar.db"]              = "无符号整型变量数据库"
$desc["ulngvar.db"]              = "无符号长整型变量数据库"
$desc["userrng.db"]              = "用户范围数据库"
$desc["userrng.key"]             = "用户范围数据库索引"
$desc["userrngi.db"]             = "用户范围输入数据库"
$desc["viewId.key"]              = "视图 ID 数据库索引"
$desc["vista.log"]               = "Vista 数据库日志"
$desc["wccoaone.taf"]            = "WinCC OA TAF 归档文件"
$desc["0000000000"]              = "0000 号段历史数据分区"
$desc["al0000000000"]            = "报警历史数据分区"
$desc["alliving"]                = "活跃报警数据分区"
$desc["aloverflow"]              = "报警溢出数据分区"
$desc["alsave"]                  = "报警保存数据分区"
$desc["ancient"]                 = "归档历史数据分区"
$desc["empty"]                   = "空数据分区"
$desc["lastval"]                 = "最新值数据分区"
$desc["save"]                    = "保存数据分区"
$desc["dplist"]                  = "数据点列表目录"
$desc["help"]                    = "帮助文档目录"
$desc["en_US.utf8"]              = "英文(美国)语言包"
$desc["zh_CN.utf8"]              = "简体中文语言包"
$desc["images"]                  = "图片资源目录"
$desc["examples"]                = "示例图片"
$desc["gedi"]                    = "GEDI 图形编辑器图片"
$desc["objects"]                 = "对象图片"
$desc["para"]                    = "参数图片"
$desc["vision"]                  = "Vision 图片"
$desc["log"]                     = "项目运行日志目录"
$desc["createDb.log"]            = "数据库创建日志"
$desc["createDb.log.data.log"]   = "数据库创建数据日志"
$desc["createDb.log.event.log"]  = "数据库创建事件日志"
$desc["createDb.log.sim.log"]    = "数据库创建模拟日志"
$desc["dbRepair.log"]            = "数据库修复日志"
$desc["pmon.MYH_HPOMEN"]         = "进程监控日志"
$desc["PVSS_II.log"]             = "WinCC OA 主进程日志"
$desc["WCCILpmon1.log"]          = "WCCOA 进程监控日志"
$desc["WCCOAtoolLogViewer1.log"] = "日志查看器日志"
$desc["msg"]                     = "系统消息目录"
$desc["panels"]                  = "面板文件目录(UI 界面)"
$desc["pictures"]                = "画面文件目录"
$desc["scripts"]                 = "CONTROL 脚本目录"
$desc["libs"]                    = "脚本库目录"
$desc["source"]                  = "源代码目录"
$desc["alertpr.key"]             = "报警处理数据库索引"
$desc["alertrd.key"]             = "报警读取数据库索引"
$desc["alertrec.db"]             = "报警记录数据库"
$desc["alertrg.key"]             = "报警范围数据库索引"
$desc["dplist.db"]               = "数据点列表数据库"
$desc["DpList.dbd"]              = "数据点列表数据库定义"
$desc["dplist.key"]              = "数据点列表数据库索引"

$maxLineLen = 0
foreach ($line in $lines) { if ($line.Length -gt $maxLineLen) { $maxLineLen = $line.Length } }
$targetCol = [Math]::Max($maxLineLen + 4, 60)

$out = @()
foreach ($line in $lines) {
    if ($line.Trim() -eq "") {
        $out += ""
    } else {
        $name = ($line -replace '^.*[+\\|]-*\s*', '').Trim()
        $d = ""
        if ($desc.ContainsKey($name)) { $d = $desc[$name] }
        $padLen = [Math]::Max(1, $targetCol - $line.Length)
        $pad = " " * $padLen
        $out += "$line$pad$d"
    }
}
$cnt = $out.Count
$out -join "`r`n" | Out-File -LiteralPath $outputFile -Encoding utf8
Write-Host "Generated $outputFile with $cnt lines"
